# central-server is the nodejs main server.

production:
  basic_auth:
    user: 'user'
    password: 'pass'
  server:
    port: 3000


development:
  basic_auth:
    user: 'user'
    password: 'pass'
  server:
    port: 3000
  amqp:
    url: 'amqp://guest:guest@localhost:5672'
    exchange:
      name: 'webhook'
      options:
        durable: true
        confirm: false
        type: 'fanout'
    routing_key_prefix: 'webhook_'
  apps:
    - 'demo'


testing:
  basic_auth:
    user: 'user'
    password: 'pass'
  server:
    port: 3000
  celery:
    unknown: 'true'
